### ISSUE TITLE
Cant remove portable light

### ISSUE THREAD

**Issue by DawnShadow** [Panakotta00/LightItUp#5] opened 2020-01-17 15:37 UTC
When deployed, the portable light cannot be removed.

**Comment by mckulich** [comment] 2020-01-19 17:03
Have same issue. I have latest version of mod installed. If it is help i have Moar Factory, Farming mod, Light it up and Renewable energy mod. Fresh game in stable branch CL 109075.

**Comment by githarnian** [comment] 2020-01-30 17:05
I can confirm this issue and adding on the following:

- When creating a portable light and leaving it in the inventory, saving and loading the game results in the portable light not being in the inventory.  The materials are still used, but the light is no longer there.
- When trying to remove the portable light, it acts as if it does, but then it does not complete the action.

**Comment by Panakotta00** [comment] 2020-03-08 11:22
This bug probably will get fixed with the SML 2.0 version but I can't ensure cause I'm not able to reproduce it.

When the new version is released and the issue still is the case, plz create a comment on that issue, thanks ^^

Sry for the late response.

**Comment by Panakotta00** [comment] 2020-03-16 12:52
Should now be fixed with v0.4.0

**Closed as completed by Panakotta00** 2020-03-16 12:52 UTC
